languaje: csharp
mono: none
dotnet: 3.1
solution: Miracleapp.API.sln

install: 
  - dolnet restore

script:
  - dotnet publish --configuration Release --runtime win-x64 /p:PublishSingleFile=true --output win-64
  - dotnet publish --configuration Release --runtime win-x86 /p:PublishSingleFile=true --output win-86
  - dotnet publish --configuration Release --runtime linix-x64 /p:PublishSingleFile=true --output linux-64
  - dotnet publish --configuration Release --runtime osx-x64 /p:PublishSingleFile=true --output onx-64

before_deploy:
  - zip -r9 win-x64.zip win-x64
  - zip -r9 win-x86.zip win-x86
  - zip -r9 linux-x64.zip linux-x64
  - zip -r9 osx-x64.zip osx-x64

deploy:
  provider: releases 
  api_key: $api_key
  file:
    - win-x64.zip
    - win-x86.zip
    - linux-x64.zip
    - osx-x64.zip
  skip_cleanup: true
  on:
    tags: true
